package codegen

import (
	"strings"
	"testing"
)

func TestPreviewSQLMatchesJavaTemplates(t *testing.T) {
	menu := int64(8)
	table := Table{
		ModuleName: "infra", BusinessName: "student", ClassName: "Student", ClassComment: "学生",
		TableName: "demo_student", TableComment: "学生表", ParentMenuID: &menu, FrontType: frontVue3Element,
	}
	columns := []Column{
		{ColumnName: "id", JavaField: "id", JavaType: "Long", PrimaryKey: true, Nullable: false},
		{ColumnName: "name", JavaField: "name", JavaType: "String", Nullable: true, HTMLType: "input", ListOperation: true, ListOperationCondition: "=", ListOperationResult: true, CreateOperation: true, UpdateOperation: true, ColumnComment: "名字"},
		{ColumnName: "create_time", JavaField: "createTime", JavaType: "LocalDateTime", Nullable: false},
		{ColumnName: "deleted", JavaField: "deleted", JavaType: "Boolean", Nullable: false},
	}
	files := previewFiles(table, columns)
	if len(files) != 14 || files[0].FilePath != "sql/sql.sql" || !strings.Contains(files[0].Code, "'学生管理'") || strings.Contains(files[0].Code, "infra:student:import") {
		t.Fatalf("文件数 %d\n%s", len(files), files[0].Code)
	}
	joined := joinPreview(files)
	if !strings.Contains(joined, "public class StudentDO") || !strings.Contains(joined, "private String name;") || strings.Contains(fileBySuffix(files, "DO.java").Code, "createTime") {
		t.Fatal(fileBySuffix(files, "DO.java").Code)
	}
	if !strings.Contains(joined, "class StudentServiceImpl") || !strings.Contains(joined, "export const StudentApi") || !strings.Contains(joined, "`/infra/student/page`") || strings.Contains(joined, "importStudent") || !strings.Contains(joined, "defineOptions({ name: 'StudentForm' })") || !strings.Contains(joined, "请输入名字") || !strings.Contains(joined, "defineOptions({ name: 'Student' })") || !strings.Contains(joined, "infra:student:export") {
		t.Fatal(joined)
	}
	if !strings.Contains(fileBySuffix(files, "DO.java").FilePath, "dal/dataobject/student/StudentDO.java") || !strings.Contains(fileBySuffix(files, "ErrorCodeConstants_手动操作.java").FilePath, "ErrorCodeConstants_手动操作.java") {
		t.Fatal(files[1].FilePath, files[3].FilePath)
	}
	h2 := h2SQL(table, columns)
	if !strings.Contains(h2, `CREATE TABLE IF NOT EXISTS "demo_student"`) || !strings.Contains(h2, `"id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY`) {
		t.Fatal(h2)
	}
	if !strings.Contains(h2, `"name" varchar,`) || !strings.Contains(h2, `"create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP`) || !strings.Contains(h2, `DELETE FROM "demo_student";`) {
		t.Fatal(h2)
	}
	if symbolCase("HTTPResponse", '-') != "http-response" || symbolCase("DictType", '-') != "dict-type" {
		t.Fatal(symbolCase("HTTPResponse", '-'), symbolCase("DictType", '-'))
	}
	same := simpleClassName(Table{ClassName: "Infra", ModuleName: "infra"})
	if same != "Infra" {
		t.Fatal(same)
	}
}

func TestTreeServiceImplDoesNotPanic(t *testing.T) {
	parent, name := int64(2), int64(3)
	table := Table{TemplateType: templateTree, ModuleName: "infra", BusinessName: "category", ClassName: "Category", ClassComment: "分类", TreeParentColumnID: &parent, TreeNameColumnID: &name}
	columns := []Column{
		{ID: 1, ColumnName: "id", JavaField: "id", JavaType: "Long", PrimaryKey: true},
		{ID: 2, ColumnName: "parent_id", JavaField: "parentId", JavaType: "Long", ColumnComment: "父编号"},
		{ID: 3, ColumnName: "name", JavaField: "name", JavaType: "String", ColumnComment: "名字"},
	}
	code := serviceImplJava(table, columns)
	if !strings.Contains(code, "CATEGORY_PARENT_ERROR") || !strings.Contains(code, "getCategoryList") || strings.Contains(code, "deleteCategoryListByIds") {
		t.Fatal(code)
	}
}

func TestPreviewRejectsUnimplementedTemplates(t *testing.T) {
	for _, tc := range []struct {
		name  string
		table Table
	}{
		{"主子表", Table{TemplateType: templateMasterNormal, FrontType: frontVue3Element}},
		{"Vben 前端", Table{TemplateType: templateOne, FrontType: 40}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if err := validateGenerationSupport(tc.table); err == nil {
				t.Fatal("未实现的模板不能生成不完整代码包")
			}
		})
	}
	if err := validateGenerationSupport(Table{TemplateType: templateTree, FrontType: frontVue3Element}); err != nil {
		t.Fatal(err)
	}
}

func joinPreview(files []PreviewFile) string {
	var b strings.Builder
	for _, file := range files {
		b.WriteString(file.Code)
		b.WriteByte('\n')
	}
	return b.String()
}

func fileBySuffix(files []PreviewFile, suffix string) PreviewFile {
	for _, file := range files {
		if strings.HasSuffix(file.FilePath, suffix) {
			return file
		}
	}
	return PreviewFile{}
}
